### ISSUE TITLE
We should dry run a transaction before accepting it to the delivery depot queue

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/payments#175]

**Comment by Guillembonet** [comment]
How we do it currently is:
1. Depot never has a client with dry run, so all transactions will get sent and mined regardless of if they will be reverted or not.
2. It's courier's responsibility to only enqueue transactions that will not get reverted.

You can't dry run any transaction in a generic way, you need to load the SC code for each of them so doing it generically in payments repo is not possible and should be the callers responsibility to do so.
