### ISSUE TITLE
Add configurable magic constant to smart contract

### ISSUE THREAD

**Issue by tadovas** [mysteriumnetwork/payments#19]
At the moment service consumer issued promises are subject to possible replay attacks:
1. Smart contract is deployed on testnet, service consumer issues valid promise which is clearable on smart contract
2. Smart contract is deplyed on mainnet, any promise issued by service consumer is valid on mainnet if service consumer reuses it's identity on mainnnet.
Solution:
Add configurable magic constatnt which can be read freely and added to promise hash before signing - that way only smart contract with same magic constant can validate/clear issued promise. Of course constants must be different on different blockchains (i.e "producetion" on mainnet and "test' on "testnet". For better transparancey - this constant can be set on contract deployment only.

**Comment by tadovas** [comment]
This magic constant can also be semantic version of contract, as on testnet we probably use some kind of rc based versions anyway

**Comment by gundas** [comment]
That "magic constant" could also be the address of the contract itself.
