### ISSUE TITLE
Fork Go-Ethereum

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/payments#200]
Go ethereum uses the standart library JSON package which is slow and inefficient. It does a lot of marshaling and unmarshaling. It would be great to do it more efficiently so we can use less memory/cpu.
- [ ] Fork go-ethereum
- [ ] Replace the JSON encoding library with `"github.com/json-iterator/go"`
- [ ] Replace that library in other repos:
  - [ ] Payments
  - [ ] Hermes
  - [ ] Observer
  - [ ] Transactor

**Comment by n10ty** [comment]
No need for this, because of: [Add registry to cache Hermes Callers](https://github.com/mysteriumnetwork/payments/pull/202)
