### ISSUE TITLE
Define a custom identity (address) type

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/payments#212]
Currently something similar [exists in node](https://github.com/mysteriumnetwork/node/blob/master/identity/identity.go) but it is not even close to good enough. We would like to define a custom type which would unify our representation of an address.

Most services now call `strings.ToLower(Address.Hex())` when needing to compare these addreses in DB funcs or return them from public facing APIs. Examples include but are not limited:
* https://github.com/mysteriumnetwork/pilvytis/blob/master/storage/dbpil/query_offchain.go#L102
* https://github.com/mysteriumnetwork/pilvytis/blob/master/server/handler/offchain.go#L186
* https://github.com/mysteriumnetwork/pilvytis/blob/master/server/handler/offchain.go#L186

What we want:
* If marshaled such an address should always be lower case
* When using it in comparisons in DB funcs it should be lower case
* When inserting it to DB it should be lower case
* It should still be easy to use and compatible with `common` package of eth library we use

**Comment by n10ty** [comment]
Too much changes and too risky
https://github.com/mysteriumnetwork/payments/pull/246
Closed for better future
