### ISSUE TITLE
Entries in `tx_delivery` should be cleaned up automatically

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/payments#222]
After a certain period of time, lets say 30 days, those entries are just simply useless. If they are delivered and are old, they should be removed.

**Comment by Guillembonet** [comment]
- [ ] add to payments repo
- [ ] pilvytis/topperupper
- [ ] hermes
- [ ] transactor

**Comment by tomasmik** [comment]
Transactor is ready for this change
