### ISSUE TITLE
Build an authentication server

### ISSUE THREAD

**Issue by Snawoot** [mysteriumnetwork/payments#229]
It became clear that our company is going to need some user authentication in order to provide services to users. Namely, it can be useful for following applications:

* VPN service (centralized, subscription-based).
* Myst Nodes (instead of internal user DB, for consolidation).
* Universe (right now it has only one static password).
* Probably for superproxy webscraping service (if we decide to make it a public self-service dashboard with automated access, like [packetstream.io](https://packetstream.io)).

All it needs to do is to authenticate user using one of configured methods (e.g. plain password) and return JWT token (similar to OAuth 2.0). Services which need to authenticate user will just validate access token and allow access granted for this user.

Note that one user may have multiple confirured authentication methods like password, social account login and so on. For starters lets make only password option, but keep that in mind designing data schema.

Also note that users may belong to different namespaces: i.e. registation database (realm) for webscraping may be different than the one for the VPN service. These accounts are completely different for these services.

Also we will need usual stuff like password resets etc.

It is also possible to consider off-the-shelf options like IdentityServer, but I doubt these are customizable enough, so we'd probably start with own simple thing.

**Comment by n10ty** [comment]
https://github.com/mysteriumnetwork/sentinel
