### ISSUE TITLE
Add a function exposing the seqNo for the given sender/receiver combo

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/payments#24]
Currently, we're implementing a sequence ID counter on the provider side. While coding this, an idea popped up. 

What happens if we lose the DB, it gets corrupted or the hard drive explodes? In that case we won't be able to know which sequence ID we're currently working with for the given consumer. 

So, to restore the sequence ID we need to expose a function on the IdentityPromises contract, to allow to lookup the last cleared sequenceID for a given receiver.

Once that is implemented, the provider can restore the state in case of a disaster. A lookup should not be expensive, so the provider can lookup which seqID it last used for the promise issuer if he does not know anything about the consumer. Query it once, store it in the database and resume normal book keeping on the local DB.

**Comment by tadovas** [comment]
It has. It is a public field named "clearedPromises" and it's purpose is exactly that - keep track of last cleared promise seqID for given payer - receiver pair. From golang binding perspective - https://github.com/mysteriumnetwork/payments/blob/master/contracts/abigen/payments.go#L639
It's a function which takes mentioned above address pairs and returns bigint which represents last cleared promise

**Comment by chompomonim** [comment]
Because of v2 of payments solution, Issue is not valid anymore.
