### ISSUE TITLE
Extract fee increase logic

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/payments#77]
Currently, transactor uses a system where transactions are stored in the database until they succeed or spend a predefined time in the pending state. Once the time is exceeded, the transactions are then retried with a bigger gas price. 

This logic is useful for most transactions and should be extracted to the payment package. We could then use the payment package in both hermes and transactor to use the same logic for both. 

The logic should abstract away a transaction, to be able to store and retry any transaction independent of the transaction type itself.

**Comment by tomasmik** [comment]
Done here: https://github.com/mysteriumnetwork/payments/pull/79

Services upgraded.
